spring.application.name=tech-it-easy
server.port=8080

# datasource PostgreSQl
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/tech-it-easy-les-12-huiswerk
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# generate schema ddl to create tables
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.boot.autoconfigure.sql.init=DEBUG
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG
